spring:
  application:
    name: Discussion

  datasource:
    url: jdbc:cassandra://localhost:9042/distcomp
    username:
    password:
  cassandra:
    local-datacenter: datacenter1
    keyspace-name: distcomp
    schema-action: create_if_not_exists

server:
  port: 24130

api:
  url: /api/v1.0
  kafka:
    request-topic: InTopic
    response-topic: OutTopic
