spring:
  application:
    name: Publisher
  datasource:
    url: jdbc:postgresql://localhost:5432/distcomp
    username: postgres
    password: postgres
  liquibase:
    change-log: classpath:db/changelog/publisher-master.xml
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 6000


server:
  port: 24110

api:
  url: /api/v1.0
  notes-url: http://localhost:24130/api/v1.0/notes
  kafka:
    request-topic: InTopic
    response-topic: OutTopic
