server:
  port: 24110
  servlet:
    context-path: /api/v1.0

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/distcomp
    username: postgres
    password: postgres

  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect=org.hibernate.dialect.PostgreSQLDialect
        ddl-auto=none

  data:
    redis:
      host: localhost
      port: 6379

  liquibase:
    change-log: classpath:db/changelog/changelog-master.xml

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: in-message:by.bsuir.publisherservice.dto.message.InTopicMessage
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.type.mapping: out-message:by.bsuir.publisherservice.dto.message.OutTopicMessage
    topic:
      request: in-topic
      response: out-topic
      create: create-topic

logging:
  level:
    org:
      springframework:
        cache: DEBUG

services:
  discussion:
    url: http://localhost:24130/api/v1.0
