services:
  postgres-publisher-service:
    container_name: postgres-publisher-service
    hostname: postgres-publisher-service
    image: postgres:alpine3.17
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: distcomp
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_AUTH_METHOD: TRUST
      PGDATA: /data/postgres
    volumes:
      - data-publisher-service:/data/postgres

  cassandra-discussion-service:
    container_name: cassandra-discussion-service
    hostname: cassandra-discussion-service
    image: cassandra:latest
    restart: unless-stopped
    ports:
      - 9042:9042
    environment:
      CASSANDRA_CLUSTER_NAME: 'distcomp'
      CASSANDRA_ENDPOINT_SNITCH: GossipingPropertyFileSnitch
      CASSANDRA_DC: DC1
      CASSANDRA_RACK: RAC1
      CASSANDRA_SEEDS: cassandra-discussion-service
    volumes:
      - data-discussion-service:/var/lib/cassandra

  zookeeper:
    container_name: zookeeper
    image: confluentinc/cp-zookeeper:latest
    hostname: zookeeper
    ports:
      - 2181:2181
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    container_name: kafka
    image: confluentinc/cp-kafka:latest
    hostname: kafka
    ports:
      - 9092:9092
    environment:
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:29092,EXTERNAL://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_BROKER_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
    depends_on:
      - zookeeper

volumes:
  data-publisher-service: { }
  data-discussion-service: { }