server:
  port: 24130
  servlet:
    context-path: /api/v1.0

spring:
  cassandra:
    keyspace-name: distcomp
    port: 9042
    contact-points: 127.0.0.1
    local-datacenter: DC1

  datasource:
    name: cassandra_datasource
    url: jdbc:cassandra://localhost:9042/distcomp?localdatacenter=DC1
    driver-class-name: com.ing.data.cassandra.jdbc.CassandraDriver
    hikari.minimum-idle: 1

  liquibase:
    url: jdbc:cassandra://localhost:9042/distcomp?localdatacenter=DC1&compliancemode=Liquibase
    driver-class-name: com.ing.data.cassandra.jdbc.CassandraDriver
    change-log: classpath:db/changelog/changelog-master.xml

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: out-message:by.bsuir.discussionservice.dto.message.OutTopicMessage
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.type.mapping: in-message:by.bsuir.discussionservice.dto.message.InTopicMessage
    topic:
      request: in-topic
      response: out-topic
      create: create-topic