server:
  port: 24130
  servlet:
    context-path: /api/v1.0

spring:
  cassandra:
    schema-action: CREATE_IF_NOT_EXISTS
    request:
      timeout: 10s
    keyspace-name: distcomp
    port: 9042
    contact-points: localhost

  kafka:
    bootstrap-servers: localhost:9092

    consumer:
      group-id: myGroup
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.value.default.type: com.poluectov.reproject.discussion.model.KafkaMessageRequestTo


    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false

kafka:
  topic:
    message:
      request: message-request
      response: message-response
  url: localhost:9092


