services:
  postgres-publisher-service:
    container_name: postgres-publisher-service
    hostname: postgres-publisher-service
    image: postgres:alpine3.17
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: distcomp
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_AUTH_METHOD: TRUST
      PGDATA: /data/postgres
    volumes:
      - data-publisher-service:/data/postgres

  cassandra-discussion-service:
    container_name: cassandra-discussion-service
    hostname: cassandra-discussion-service
    image: cassandra:latest
    restart: unless-stopped
    ports:
      - 9042:9042
    environment:
      CASSANDRA_CLUSTER_NAME: 'distcomp'
      CASSANDRA_ENDPOINT_SNITCH: GossipingPropertyFileSnitch
      CASSANDRA_DC: DC1
      CASSANDRA_RACK: RAC1
      CASSANDRA_SEEDS: cassandra-discussion-service
    volumes:
      - data-discussion-service:/var/lib/cassandra

volumes:
  data-publisher-service: { }
  data-discussion-service: { }